//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int TourId { get; set; }
        public int HotelId { get; set; }
        public int TransportationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime BookDate { get; set; }
        public int NumberOfAdults { get; set; }
        public int NumberOfChildren { get; set; }
        public double TotalPrice { get; set; }
        public int Status { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual Transportation Transportation { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
